export enum StateTN {
  Tunis = 'Tunis',
  Ariana = 'Ariana',
  BenArous = 'Ben Arous',
  Manouba = 'Manouba',
  Nabeul = 'Nabeul',
  Zaghouan = 'Zaghouan',
  Bizerte = 'Bizerte',
  Beja = 'Béja',
  Jendouba = 'Jendouba',
  Kef = 'Le Kef',
  Siliana = 'Siliana',
  Kairouan = 'Kairouan',
  Kasserine = 'Kasserine',
  SidiBouzid = 'Sidi Bouzid',
  Sousse = 'Sousse',
  Monastir = 'Monastir',
  Mahdia = 'Mahdia',
  Sfax = 'Sfax',
  Gafsa = 'Gafsa',
  Tozeur = 'Tozeur',
  Kebili = 'Kebili',
  Gabes = 'Gabès',
  Medenine = 'Medenine',
  Tataouine = 'Tataouine',
}
export const CitiesByStateTN: Record<StateTN, readonly string[]> = {
  [StateTN.Tunis]: ['Tunis', 'La Marsa', 'Carthage', 'Le Kram', 'La Goulette', 'Sidi Bou Saïd'],
  [StateTN.Ariana]: ['Ariana', 'Raoued', 'Kalaat el-Andalous', 'Soukra'],
  [StateTN.BenArous]: ['Ben Arous', 'Ezzahra', 'Hammam Lif', 'Hammam Chatt', 'Rades', 'Mornag'],
  [StateTN.Manouba]: ['Manouba', 'Douar Hicher', 'Oued Ellil', 'Tebourba'],
  [StateTN.Nabeul]: ['Nabeul', 'Hammamet', 'Beni Khiar', 'Kelibia', 'Menzel Temime', 'Grombalia'],
  [StateTN.Zaghouan]: ['Zaghouan', 'Zaouiet Jedidi', 'Bir Mcherga'],
  [StateTN.Bizerte]: ['Bizerte', 'Menzel Bourguiba', 'Mateur', 'Ghar El Melh', 'Ras Jebel'],
  [StateTN.Beja]: ['Béja', 'Téboursouk', 'Testour', 'Nefza'],
  [StateTN.Jendouba]: ['Jendouba', 'Tabarka', 'Aïn Draham', 'Bou Salem'],
  [StateTN.Kef]: ['Le Kef', 'Tajerouine', 'Sakiet Sidi Youssef'],
  [StateTN.Siliana]: ['Siliana', 'Gaafour', 'Bargou'],
  [StateTN.Kairouan]: ['Kairouan', 'Haffouz', 'Sbikha', 'Chebika'],
  [StateTN.Kasserine]: ['Kasserine', 'Sbeitla', 'Fériana', 'Thala'],
  [StateTN.SidiBouzid]: ['Sidi Bouzid', 'Meknassy', 'Regueb', 'Jilma'],
  [StateTN.Sousse]: ['Sousse', 'Msaken', 'Ezzouhour', 'Hammam Sousse', 'Akouda'],
  [StateTN.Monastir]: ['Monastir', 'Sahline', 'Jemmal', 'Ksar Hellal', 'Ksibet el-Mediouni'],
  [StateTN.Mahdia]: ['Mahdia', 'Chebba', 'El Jem', 'Ksour Essef'],
  [StateTN.Sfax]: ['Sfax', 'Sakiet Ezzit', 'Sakiet Eddaïer', 'Agareb', 'Jebeniana', 'Kerkennah'],
  [StateTN.Gafsa]: ['Gafsa', 'Redeyef', 'Métlaoui', 'Mdhilla'],
  [StateTN.Tozeur]: ['Tozeur', 'Nefta', 'Degache'],
  [StateTN.Kebili]: ['Kebili', 'Douz', 'Souk Lahad'],
  [StateTN.Gabes]: ['Gabès', 'Mareth', 'Matmata', 'Chenini Nahal'],
  [StateTN.Medenine]: ['Medenine', 'Zarzis', 'Ben Guerdane', 'Djerba Houmt Souk', 'Midoun'],
  [StateTN.Tataouine]: ['Tataouine', 'Ghomrassen', 'Dhehiba', 'Remada'],
} as const;